### ISSUE TITLE
Support for schema references 

### ISSUE THREAD

**Issue by dstendardi** [arkiaconsulting/terraform-provider-confluent-schema-registry#13]
## Description of the problem

Confluent introduced support for schema references which are pretty handy when you want to [store multiple event types in a single topic](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/).

## Proposed solution

We would like to contribute with MR and implement the following changes :

```
resource "schemaregistry_schema"  "a" {
    schema = ".."
    subject = "..."
}

resource "schemaregistry_schema"  "b" {
    schema = ".."
    subject = "..."
    
    reference {
        name = "..."
        subject = schemaregistry_schema.a.subject
        version =  schemaregistry_schema.a.version
    }
}
```

Given the schema `a` is updated, the schema `b` version should be updated and its reference to schema `a` version also.
If one wants to stick with a version he can just hardcode it in the `reference` block

We will need to update https://github.com/riferrei/srclient  from `0.3.0` to `0.3.1`.

We are open to contrib with a MR if this changes fits in your plan.

**Comment by arkiaman** [comment]
Feature added in v0.7.0
