### ISSUE TITLE
Support for DataSource in a given schema version

### ISSUE THREAD

**Issue by noureddineseddik** [arkiaconsulting/terraform-provider-confluent-schema-registry#15]
**Description of the problem**
Existing `dataSource` implementation always sticks to the `latest` available version of the registry's schema.
An older version of a schema could still be in use (e.g.: in a topic with references).

**Proposed solution**
- switch the data source version field from `computed` to `optional`
- load a specific version when that field is set, else keep existing logic (fetch `latest`)

The `resource` implementation remains **unchanged** and always handles the `latest` available version in the registry.

**Example**
1. Declare an event schema and a topic's one with reference as usual
```
resource "schemaregistry_schema" "user_added" {
  subject = "MyTopic-akc.test.userAdded-value"
  schema  = file("./userAdded.avsc")
}

resource "schemaregistry_schema" "with_reference" {
  subject = "with-reference"
  schema = "[\"akc.test.userAdded\"]"

  reference {
    name = "akc.test.userAdded"
    subject = schemaregistry_schema.user_added.subject
    version = schemaregistry_schema.user_added.version
  }
}
```

2. Event schema evolves, topic now refers to v1 event schema with dataSource
```
resource "schemaregistry_schema" "user_added" {
  subject = "MyTopic-akc.test.userAdded-value"
  schema  = file("./userAdded_v2.avsc")
}

data "schemaregistry_schema" "user_added_v1" {
  subject = "MyTopic-akc.test.userAdded-value"
  version = 1
}

resource "schemaregistry_schema" "with_reference" {
  subject = "with-reference"
  schema = "[\"akc.test.userAdded\"]"

  reference {
    name = "akc.test.userAdded"
    subject = data.schemaregistry_schema.user_added_v1.subject
    version = data.schemaregistry_schema.user_added_v1.version
  }
}
```

**Comment by arkiaman** [comment]
Resolved in v0.8.0
